name: Update README

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get languages used
        run: |
          languages=$(curl -s https://api.github.com/users/AbanoubSeddik/repos | jq -r '.[].language' | sort | uniq -c | sort -rn)
          echo "## Most Used Languages" > languages.md
          echo "$languages" >> languages.md

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat languages.md >> README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with most used languages'
          git push https://AbanoubSeddik:${{ secrets.GH_TOKEN }}@github.com/AbanoubSeddik/AbanoubSeddik.git
